# Generated by Django 4.1.5 on 2023-01-15 07:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wallapp', '0003_abstract_amoled_animal_dark_girl_movies_nature_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='wallupload',
            new_name='walluploadmodel',
        ),
    ]
