# Generated by Django 4.1.5 on 2023-01-15 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallapp', '0004_rename_wallupload_walluploadmodel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='abstract',
            name='image',
            field=models.FileField(upload_to='wallapp/static'),
        ),
        migrations.AlterField(
            model_name='amoled',
            name='image',
            field=models.FileField(upload_to='wallapp/static/amoled'),
        ),
        migrations.AlterField(
            model_name='animal',
            name='image',
            field=models.FileField(upload_to='wallapp/static'),
        ),
        migrations.AlterField(
            model_name='dark',
            name='image',
            field=models.FileField(upload_to='wallapp/static'),
        ),
        migrations.AlterField(
            model_name='girl',
            name='image',
            field=models.FileField(upload_to='wallapp/static'),
        ),
        migrations.AlterField(
            model_name='movies',
            name='image',
            field=models.FileField(upload_to='wallapp/static'),
        ),
        migrations.AlterField(
            model_name='nature',
            name='image',
            field=models.FileField(upload_to='wallapp/static'),
        ),
    ]
