# Generated by Django 4.1.5 on 2023-01-15 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallapp', '0005_alter_abstract_image_alter_amoled_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='abstract',
            name='image',
            field=models.FileField(upload_to='wallapp/static/abstract'),
        ),
        migrations.AlterField(
            model_name='animal',
            name='image',
            field=models.FileField(upload_to='wallapp/static/animal'),
        ),
        migrations.AlterField(
            model_name='dark',
            name='image',
            field=models.FileField(upload_to='wallapp/static/dark'),
        ),
        migrations.AlterField(
            model_name='girl',
            name='image',
            field=models.FileField(upload_to='wallapp/static/girl'),
        ),
        migrations.AlterField(
            model_name='movies',
            name='image',
            field=models.FileField(upload_to='wallapp/static/movies'),
        ),
        migrations.AlterField(
            model_name='nature',
            name='image',
            field=models.FileField(upload_to='wallapp/static/nature'),
        ),
    ]
