# Generated by Django 4.1.5 on 2023-01-31 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallapp', '0006_alter_abstract_image_alter_animal_image_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='uregmodel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullname', models.CharField(max_length=30)),
                ('username', models.CharField(max_length=30)),
                ('email', models.EmailField(max_length=254)),
                ('password', models.CharField(max_length=30)),
            ],
        ),
        migrations.DeleteModel(
            name='walluploadmodel',
        ),
    ]
