# Generated by Django 4.1.5 on 2023-02-01 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallapp', '0007_uregmodel_delete_walluploadmodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='amoleds',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.FileField(upload_to='')),
                ('imagename', models.CharField(max_length=100)),
                ('category', models.CharField(max_length=30)),
            ],
        ),
    ]
