# Generated by Django 4.1.5 on 2023-02-02 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallapp', '0008_amoleds'),
    ]

    operations = [
        migrations.CreateModel(
            name='abstracts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.FileField(upload_to='')),
                ('imagename', models.CharField(max_length=100)),
                ('category', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='animals',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.FileField(upload_to='')),
                ('imagename', models.CharField(max_length=100)),
                ('category', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='darks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.FileField(upload_to='')),
                ('imagename', models.CharField(max_length=100)),
                ('category', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='girls',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.FileField(upload_to='')),
                ('imagename', models.CharField(max_length=100)),
                ('category', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='moviess',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.FileField(upload_to='')),
                ('imagename', models.CharField(max_length=100)),
                ('category', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='natures',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.FileField(upload_to='')),
                ('imagename', models.CharField(max_length=100)),
                ('category', models.CharField(max_length=30)),
            ],
        ),
        migrations.DeleteModel(
            name='abstract',
        ),
        migrations.DeleteModel(
            name='amoled',
        ),
        migrations.DeleteModel(
            name='animal',
        ),
        migrations.DeleteModel(
            name='dark',
        ),
        migrations.DeleteModel(
            name='girl',
        ),
        migrations.DeleteModel(
            name='movies',
        ),
        migrations.DeleteModel(
            name='nature',
        ),
    ]
